baseURL = "https://nofegreen.github.io/"
languageCode = "en-us"
title = "Nofe Green"
author = "@NofeGreen"
theme = "jeffprod"
canonifyurls = true

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

    # Number of blog posts in each pagination page
paginator = 6
paginate = 3
